export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const GET_TESTIMONIALS = 'GET_TESTIMONIALS';
export const SORT_PRICE = 'SORT_PRICE';
export const USER = 'USER';
